#include<cstdio>
#include<cstring>
#include<algorithm>
using namespace std;
inline int read(){
    int ret=0;char c=getchar();
    while((c>'9')||(c<'0'))c=getchar();
    while((c>='0')&&(c<='9'))ret=(ret<<1)+(ret<<3)+c-'0',c=getchar();
    return ret;
}
int tt,t,x,y;
int main()
{
	freopen("jump.in","r",stdin);
	freopen("jump.out","w",stdout);
	t=read();
	while(t--)
	{
		x=read();
		y=read();
		x=abs(x);
		y=abs(y);
		if(x<y)swap(x,y);
		if(x==y)
		{
			if(x==0)puts("0");
			if(x==1)puts("2");
			if(x==2)puts("4");
			if(x==3)puts("2");
			if(x>=4)printf("%d\n",(x-1)/3*2+2);
			continue;
		}
		if(x==y+1)
		{
			if(y==0)puts("3");
			if(y==1)puts("1");
			if(y>=2)printf("%d\n",(y+1)/3*2+1);
			continue;
		}
		if((x-y)%4==2)
		{
			if(y<=2) 
			{
			  printf("%d\n",(x-y+2)/4*2);
			  continue;
		    }
		    if(y<=x-y)
		    { 
		    	printf("%d\n",(x-y+2)/4*2+(y+1)/4*2);
		    	continue;
			}
		    tt=y-(x-y)-1;
		    printf("%d\n",x-y+(tt+3)/3*2);
		}
		if((x-y)%4==3)
		{
			if(y>x-y+1)
			{
				tt=y-(x-y+1);
				printf("%d\n",x-y+tt/3*2+2);
				continue;
			}
			printf("%d\n",(x-y+1)/4*2+1+y/4*2);
		}
		if((x-y)%4==0) 
		{
			if(y==0)
			{
				printf("%d\n",x/4*2);
				continue;
			}
			if(y<=x-y)
			{
		        printf("%d\n",(x-y)/4*2+(y+3)/4*2);
		        continue;
		    }
		    tt=y-(x-y);
		    printf("%d\n",x-y+(tt+2)/3*2);
		}
		if((x-y)%4==1)
		{
			if(y<=1)
			{
				printf("%d\n",(x-y)/4*2+1);
				continue;
			}
			if(y<=x-y)
			{
				printf("%d\n",(x-y)/4*2+1+(y+2)/4*2);
				continue;
			}
			tt=y-(x-y);
			printf("%d\n",(x-y)+(tt+2)/3*2);
		}
	}
}
